# -*- coding: utf-8 -*-
"""CVFinalProject_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpTRFOgMdlx_t3OaMaVKaViSCQnwWTrx

# **Project 2: Joint Detection of AI-Generated Images and Post-Processing Alterations in Real-World Scenarios**

#**Imports**
"""

import

"""#**Globals**"""



"""# **Utils**"""



"""#**Data**"""



"""#**Network**"""



"""# **Train**"""



"""#**Test**"""

